% DTG config
DTG_config.constructor_fn = @gpib;
DTG_config.constructor_args = {'ni', 0, 27, ...
                               'OutputBufferSize', 512, ...
                               'EOSCharCode', 'LF', ...
                               'EOIMode', 'on', ...
                               'EOSMode', 'none'};


% pulse shaper config
pshaper_config.constructor = @serial;
pshaper_config.constructor_args = {'COM3', ...
                                   'BaudRate', 115200, ...
                                   'OutputBufferSize', 512, ...
                                   'DataBits', 8, ...
                                   'Parity', 'none', ...
                                   'StopBits', 1};
pshaper_config.cntrlf = @AD5764;
pshaper_config.max_step = 0.05;
pshaper_config.wait = 0.1;
pshaper_config.address = [1, 2, 3, 4];
pshaper_config.DCvals = [0, 0, 0, 0];

% watd (MSO44) config
watd_config.RemoteHost = '169.254.9.11';
watd_config.RemotePort = 4000;
watd_config.constructor_args = {'Type', 'tcpip', ...
                                'RemoteHost', watd_config.RemoteHost, ...
                                'RemotePort', watd_config.RemotePort, ...
                                'Tag', ''};
watd_config.InputBufferSize = 8192;
watd_config.ch = 1;
watd_config.avg = 10240;

% save as a .mat
path = 'C:\Users\avdif\Documents\MATLAB\matlab_pulsing\pulsed_Rbalance\MSO44_trial_inst_config.mat';
save(path, 'DTG_config', 'pshaper_config', 'watd_config');